### ISSUE TITLE
Suporte a Python 3.10

### ISSUE THREAD

**Issue by daltonmatos** [async-worker/async-worker#26]
Vamos adicionar suporte a python 3.10 para isso precisamos:

- [x] Atualizar aiologger para 0.7.0 (https://github.com/async-worker/aiologger/issues/18)
- [x] Atualizar aiohttp para a próxima versão compatível com py3.10
- [x] Remover totalmente a dependência do asynctest
---
PR: https://github.com/async-worker/async-worker/pull/27

**Comment by timotta** [comment]
Seria necessário também atualizar a versão do aioamqp (Para acabar com os warnings) e para abraçar o python3.11 seria necessário também parar de usar o async-test.

**Comment by daltonmatos** [comment]
Sim sim, @timotta. Acho inclusive que a remoção do asynctest é o que vai dar mais trabalho.

**Comment by timotta** [comment]
@daltonmatos estou no momento trabalhando nesse PR: https://github.com/async-worker/async-worker/pull/27 async test já ta fechado

**Comment by timotta** [comment]
@daltonmatos acredito que teriamos que deprecar python 3.7 para uma nova versão. O CI está rodando lá, mas com certeza falhará pois as libs alternativas ao async-test só estão presentes apartir de python 3.8

**Comment by timotta** [comment]
No PR:

**Done:** Atualizar aiologger para 0.7.0 (https://github.com/async-worker/aiologger/issues/18)
**Done:** Atualizar aiohttp para a próxima versão compatível com py3.10
**Done:** Remover totalmente a dependência do asynctest

Agora vou realizar uns testes em projetos nossos aqui com essa versão

**Comment by daltonmatos** [comment]
Implementado no PR https://github.com/async-worker/async-worker/pull/27
