### ISSUE TITLE
Erro ao usar async worker com python 3.11

### ISSUE THREAD

**Issue by RobsonRocha** [async-worker/async-worker#33]
Acredito que atualizar a versão do pydantic para maior que 1.8 já resolva.
Segue o problema abaixo:

collecting ... 
test_consumer_user_strike_judger.py:None (test_consumer_user_strike_judger.py)
test_consumer_user_strike_judger.py:4: in <module>
    from src.handle.event_handle import EventHandle
../src/handle/event_handle.py:1: in <module>
    from ad_moderation_consumer.service.evaluator import Evaluator
../venv/lib/python3.11/site-packages/ad_moderation_consumer/__init__.py:7: in <module>
    from .consumer import Consumer  # noqa
../venv/lib/python3.11/site-packages/ad_moderation_consumer/consumer.py:4: in <module>
    from asyncworker.easyqueue.queue import DeliveryModes
../venv/lib/python3.11/site-packages/asyncworker/__init__.py:1: in <module>
    from asyncworker.app import App
../venv/lib/python3.11/site-packages/asyncworker/app.py:6: in <module>
    from asyncworker.conf import logger
../venv/lib/python3.11/site-packages/asyncworker/conf.py:5: in <module>
    from pydantic import BaseSettings
../venv/lib/python3.11/site-packages/pydantic/__init__.py:2: in <module>
    from . import dataclasses
../venv/lib/python3.11/site-packages/pydantic/dataclasses.py:7: in <module>
    from .main import create_model, validate_model
../venv/lib/python3.11/site-packages/pydantic/main.py:361: in <module>
    class BaseModel(Representation, metaclass=ModelMetaclass):
../venv/lib/python3.11/site-packages/pydantic/main.py:354: in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
../venv/lib/python3.11/site-packages/pydantic/utils.py:235: in generate_model_signature
    if config.extra is config.extra.allow:
../../../.pyenv/versions/3.11.0a7/lib/python3.11/enum.py:169: in __get__
    raise AttributeError(
E   AttributeError: <enum 'Extra'> member has no attribute 'allow'

**Comment by daltonmatos** [comment]
Oi @RobsonRochak, tudo bem?

Consegue postar o output do `pip freeze` onde você rodou esse código, por favor?

Valeu!!

**Comment by daltonmatos** [comment]
Confirma também a versão do python. Era a `3.11.0a7`? Consegue re-rodar na última `3.11.x` (`3.11.4`)?

**Comment by RobsonRocha** [comment]
Perdão pela demora.
ad-moderation-consumer==1.0.2
aioamqp==0.15.0
aiohttp==3.8.4
aiologger==0.7.0
aiosignal==1.3.1
appnope==0.1.3
aresponses==2.1.6
asttokens==2.2.1
async-timeout==4.0.2
async-worker==0.20.0
asynctest==0.13.0
attrs==23.1.0
backcall==0.2.0
barterdude==1.3.1
black==23.3.0
cached-property==1.5.1
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
contextvars==2.4
coverage==7.2.7
decorator==5.1.1
executing==1.2.0
flake8==6.0.0
frozenlist==1.3.3
idna==3.4
immutables==0.19
iniconfig==2.0.0
ipdb==0.13.13
ipython==8.14.0
isort==5.12.0
jedi==0.18.2
json-logging==1.3.0
jsonschema==3.2.0
matplotlib-inline==0.1.6
mccabe==0.7.0
multidict==6.0.4
mypy-extensions==1.0.0
nose==1.3.7
packaging==23.1
pamqp==3.2.1
parso==0.8.3
pathspec==0.11.1
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==3.5.3
pluggy==1.0.0
prometheus-client==0.7.1
prompt-toolkit==3.0.38
ptyprocess==0.7.0
pure-eval==0.2.2
pycodestyle==2.10.0
pydantic==1.7.4
pyflakes==3.0.1
Pygments==2.15.1
pyrsistent==0.19.3
pytest==7.3.0
pytest-asyncio==0.21.0
pytest-cov==4.0.0
pytest-mock==3.10.0
python-json-logger==2.0.1
requests==2.28.2
six==1.16.0
stack-data==0.6.2
traitlets==5.9.0
urllib3==1.26.16
wcwidth==0.2.6
yarl==1.9.2

Alterei pra 3.11.2 e funcionou.

**Comment by daltonmatos** [comment]
Hmm boa! Então de fato é compatível com 3.11.x né?

Mas acho que vou tentar rodar os testes usando o pydantic mais novo para ver se há compatibilidade.

**Comment by daltonmatos** [comment]
Fechando issue pois confirmamos que o python 3.11.2 fucnionou. Rodei os testes com python 3.11.6 e todos passaram também. Vamos fazer o update do pydantic em outra isue/PR. 👍🏽
